apiVersion: apps/v1
kind: Deployment
metadata:
  name: indichess-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indichess-frontend
  template:
    metadata:
      labels:
        app: indichess-frontend
    spec:
      containers:
        - name: indichess-frontend
          image: indichess-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: indichess-frontend
spec:
  type: NodePort
  selector:
    app: indichess-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
