apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-communication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-communication-service
  template:
    metadata:
      labels:
        app: internal-communication-service
    spec:
      containers:
        - name: internal-communication-service
          image: indichess-internal-communication-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: internal-communication-service
spec:
  selector:
    app: internal-communication-service
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
