apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
    spec:
      containers:
        - name: match-service
          image: indichess-match-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/indichess?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
            - name: MATCH_DB_USERNAME
              value: "root"
            - name: MATCH_DB_PASSWORD
              value: "root"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://internal-communication-service:8761/eureka/"
            - name: APP_WEBSOCKET_ALLOWED_ORIGINS
              value: "http://localhost:3000"
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: match-service
spec:
  selector:
    app: match-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
